import Head from 'next/head';

export async function getServerSideProps(context:any) {
    // const id = context.params.id;
    // const response = await axios.get(`${getBaseurl}/api/board/0/${id}`);
  const a= await setTimeout(()=> 'sssss',5000)
  console.log("a :",a);
    return {
      props: {a:a  },
    };
  } 


export default function TestHTML(props: any) {
    console.log(props)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>test222</h1>
      </main>
    </>
  );
}
